import { Track, Car } from './types';

// --- TIME & WEATHER DEFINITIONS ---

// 1. Time Lists based on user input
const TIMES_STANDARD = [
  "Dawn", "Sunrise", "Early Morning", "Late Morning", 
  "Afternoon", "Evening", "Sunset", "Twilight", "Night"
];

const TIMES_EXTENDED_24H = [
  "Early Dawn", "Dawn", "Sunrise", "Early Morning", "Late Morning", 
  "Afternoon", "Evening", "Sunset", "Twilight", "Night", "Midnight"
];

const TIMES_LIMITED_DAY = [
  "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset"
];

const TIMES_LIMITED_DAY_PLUS = [
  "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight"
];

// 2. Weather Lists based on user input

// Common "Dry" weather codes (S01-S18, C01-C06)
const WEATHER_DRY = [
  "S01 | Dry, Cloudless and Pleasant",
  "S02 | Dry and Pleasant with a Few Clouds",
  "S03 | Dry, Cloudy and Pleasant",
  "S04 | Dry, Cloudy and Sunny",
  "S05 | Misty, Cloudless and Sunny",
  "S06 | Humid, Cloudless and Pleasant",
  "S07 | Humid and Pleasant with a Few Clouds",
  "S08 | Humid, Sunny and Cloudy",
  "S09 | Humid and Sunny with Lots of Clouds",
  "S10 | Misty and Sunny with Lots of Clouds",
  "S11 | Sunny with Alpine Mist",
  "S12 | Sunny with Lots of Monsoon Clouds",
  "S13 | Sunny with a Few Monsoon Clouds",
  "S14 | Sunny with Lots of Monsoon Clouds",
  "S15 | Hazy, Cloudless and Pleasant",
  "S16 | Hazy and Sunny with a Few Clouds",
  "S17 | Hazy, Cloudy and Sunny",
  "S18 | Hazy, Cloudy and Sunny",
  "C01 | Cloudy and Bright",
  "C02 | Cloudy and Warm",
  "C03 | Cloudy and Dark",
  "C04 | Cloudy and Chilly",
  "C05 | Cloudy",
  "C06 | Thick Clouds"
];

// Rain codes (R01-R08)
const WEATHER_RAIN = [
  "R01 | Light Drizzle",
  "R02 | Cloudless with Warm Rain",
  "R03 | Light Rain",
  "R04 | Cloudy with Rain",
  "R05 | Cloudy with Rain",
  "R06 | Thick Cloud with Rain",
  "R07 | Cloudy with Torrential Rain",
  "R08 | Thick Cloud with Torrential Rain"
];

const WEATHER_ALL = [...WEATHER_DRY, ...WEATHER_RAIN];

// --- EXPORTED GLOBALS (For fallback/types) ---

export const TIMES_OF_DAY = TIMES_STANDARD; 
export const WEATHER_TYPES = WEATHER_ALL;

// --- CAR LIST ---
export const CARS: Car[] = [
  { name: "1932 Ford Roadster" },
  { name: "AFEELA 1 '26" },
  { name: "AFEELA Prototype 2024" },
  { name: "Abarth 1500 Biposto Bertone B.A.T 1 '52" },
  { name: "Abarth 500 '09" },
  { name: "Alfa Romeo 155 2.5 V6 TI '93" },
  { name: "Alfa Romeo 4C Gr.3" },
  { name: "Alfa Romeo 4C Gr.3 Road Car" },
  { name: "Alfa Romeo 4C Gr.4" },
  { name: "Alfa Romeo 4C Launch Edition '14" },
  { name: "Alfa Romeo 8C 2900B Touring Berlinetta '38" },
  { name: "Alfa Romeo 8C Competizione '08" },
  { name: "Alfa Romeo GIULIA TZ2 carrozzata da ZAGATO '65" },
  { name: "Alfa Romeo Giulia GTAm '20" },
  { name: "Alfa Romeo Giulia Sprint GT Veloce '67" },
  { name: "Alfa Romeo MiTo 1.4 T Sport '09" },
  { name: "Alpine A110 1600S '72" },
  { name: "Alpine A110 Première Édition '17" },
  { name: "Alpine A220 Race Car '68" },
  { name: "Alpine Vision Gran Turismo" },
  { name: "Alpine Vision Gran Turismo 2017" },
  { name: "Alpine Vision Gran Turismo Race Mode" },
  { name: "Amuse NISMO 380RS Super Leggera" },
  { name: "Amuse S2000 GT1 Turbo" },
  { name: "Aston Martin DB11 '16" },
  { name: "Aston Martin DB3S '53" },
  { name: "Aston Martin DB5 '64" },
  { name: "Aston Martin DBR9 GT1 '10" },
  { name: "Aston Martin DP-100 Vision Gran Turismo" },
  { name: "Aston Martin One-77 '11" },
  { name: "Aston Martin V12 Vantage GT3 '12" },
  { name: "Aston Martin V8 Vantage S '15" },
  { name: "Aston Martin Valkyrie '21" },
  { name: "Aston Martin Vantage '18" },
  { name: "Aston Martin Vantage Gr.4" },
  { name: "Aston Martin Vulcan '16" },
  { name: "Audi R18 '16" },
  { name: "Audi R18 TDI '11" },
  { name: "Audi R8 4.2 FSI R tronic '07" },
  { name: "Audi R8 Coupé V10 plus '16" },
  { name: "Audi R8 LMS '15" },
  { name: "Audi R8 LMS Evo '19" },
  { name: "Audi RS 5 Turbo DTM '19" },
  { name: "Audi Sport quattro S1 Pikes Peak '87" },
  { name: "Audi TT Coupé 3.2 quattro '03" },
  { name: "Audi TT Cup '16" },
  { name: "Audi TTS Coupé '09" },
  { name: "Audi TTS Coupé '14" },
  { name: "Audi Vision Gran Turismo" },
  { name: "Audi e-tron Vision Gran Turismo" },
  { name: "Autobianchi A112 Abarth '85" },
  { name: "BAC Mono '16" },
  { name: "BMW 3.0 CSL '71" },
  { name: "BMW 3.0 CSL '73" },
  { name: "BMW M2 Competition '18" },
  { name: "BMW M3 '89" },
  { name: "BMW M3 '97" },
  { name: "BMW M3 Coupé '03" },
  { name: "BMW M3 Coupé '07" },
  { name: "BMW M3 GT '11" },
  { name: "BMW M3 Sport Evolution '89" },
  { name: "BMW M4 Coupé '14" },
  { name: "BMW M4 Gr.4" },
  { name: "BMW M4 Safety Car" },
  { name: "BMW M6 GT3 Endurance Model '16" },
  { name: "BMW M6 GT3 Sprint Model '16" },
  { name: "BMW McLaren F1 GTR Race Car '97" },
  { name: "BMW Vision Gran Turismo" },
  { name: "BMW Z4 3.0i '03" },
  { name: "BMW Z4 GT3 '11" },
  { name: "BMW Z8 '01" },
  { name: "BMW i3 '15" },
  { name: "BVLGARI Aluminium Vision Gran Turismo" },
  { name: "Bugatti Chiron '16" },
  { name: "Bugatti Veyron 16.4 '13" },
  { name: "Bugatti Veyron Gr.4" },
  { name: "Bugatti Vision Gran Turismo" },
  { name: "Bugatti Vision Gran Turismo (Gr.1)" },
  { name: "Chaparral 2J '70" },
  { name: "Chevrolet Camaro SS '16" },
  { name: "Chevrolet Camaro Z28 '69" },
  { name: "Chevrolet Camaro ZL1 1LE Package '18" },
  { name: "Chevrolet Chaparral 2X Vision Gran Turismo" },
  { name: "Chevrolet Chevelle SS 454 Sport Coupé '70" },
  { name: "Chevrolet Corvette (C1) '58" },
  { name: "Chevrolet Corvette C7 Gr.3" },
  { name: "Chevrolet Corvette C7 Gr.3 Road Car" },
  { name: "Chevrolet Corvette C7 Gr.4" },
  { name: "Chevrolet Corvette C7 Stingray '14" },
  { name: "Chevrolet Corvette C7 ZR1 '19" },
  { name: "Chevrolet Corvette C8 Stingray '20" },
  { name: "Chevrolet Corvette CX Concept '25" },
  { name: "Chevrolet Corvette CX.R Vision Gran Turismo Concept" },
  { name: "Chevrolet Corvette Sting Ray Sport Coupe (C2) '63" },
  { name: "Chevrolet Corvette Stingray Convertible (C3) '69" },
  { name: "Chevrolet Corvette Stingray L46 350 (C3) '69" },
  { name: "Chevrolet Corvette Stingray Racer Concept '59" },
  { name: "Chevrolet Corvette Z06 (C5) '01" },
  { name: "Chevrolet Corvette ZR-1 (C4) '89" },
  { name: "Chevrolet Corvette ZR1 (C6) '09" },
  { name: "Chris Holstrom Concepts 1967 Chevy Nova" },
  { name: "Citroën BX 19 TRS '87" },
  { name: "Citroën DS 21 Pallas '70" },
  { name: "DAIHATSU COPEN RJ Vision Gran Turismo" },
  { name: "DMC DeLorean S2 '04" },
  { name: "DS 3 Racing '11" },
  { name: "Daihatsu Copen Active Top '02" },
  { name: "Dallara SF19 Super Formula / Honda '19" },
  { name: "Dallara SF19 Super Formula / Toyota '19" },
  { name: "Dallara SF23 Super Formula/Honda '23" },
  { name: "Dallara SF23 Super Formula/Toyota '23" },
  { name: "De Tomaso Mangusta '69" },
  { name: "De Tomaso Pantera '71" },
  { name: "Dodge Challenger R/T '70" },
  { name: "Dodge Challenger SRT Demon '18" },
  { name: "Dodge Charger R/T 426 Hemi '68" },
  { name: "Dodge Charger SRT Hellcat '15" },
  { name: "Dodge Charger SRT Hellcat Safety Car" },
  { name: "Dodge SRT Tomahawk GTS-R Vision Gran Turismo" },
  { name: "Dodge SRT Tomahawk S Vision Gran Turismo" },
  { name: "Dodge SRT Tomahawk Vision Gran Turismo (Gr.1)" },
  { name: "Dodge SRT Tomahawk X Vision Gran Turismo" },
  { name: "Dodge Super Bee '70" },
  { name: "Dodge Viper GTS '02" },
  { name: "Dodge Viper GTS '13" },
  { name: "Dodge Viper Gr.4" },
  { name: "Dodge Viper SRT GT3-R '15" },
  { name: "Dodge Viper SRT10 Coupe '06" },
  { name: "Eckert's Rod & Custom Mach Forty" },
  { name: "Enzo Ferrari '02" },
  { name: "FIAT 500 1.2 8V Lounge SS '08" },
  { name: "FIAT 500 F '68" },
  { name: "FIAT Abarth 595 Esseesse '70" },
  { name: "FIAT Panda 30 CL '85" },
  { name: "Ferrari 250 GT Berlinetta passo corto '61" },
  { name: "Ferrari 250 GTO '62" },
  { name: "Ferrari 296 GT3 '23" },
  { name: "Ferrari 296 GTB '22" },
  { name: "Ferrari 308 GTB '75" },
  { name: "Ferrari 330 P4 '67" },
  { name: "Ferrari 365 GTB4 '71" },
  { name: "Ferrari 430 Scuderia '07" },
  { name: "Ferrari 458 Italia '09" },
  { name: "Ferrari 458 Italia GT3 '13" },
  { name: "Ferrari 458 Italia Gr.4" },
  { name: "Ferrari 500 Mondial Pinin Farina Coupe '54" },
  { name: "Ferrari 512 BB '76" },
  { name: "Ferrari 812 Superfast '17" },
  { name: "Ferrari Dino 246 GT '71" },
  { name: "Ferrari F12berlinetta '12" },
  { name: "Ferrari F40 '92" },
  { name: "Ferrari F430 '06" },
  { name: "Ferrari F50 '95" },
  { name: "Ferrari F8 Tributo '19" },
  { name: "Ferrari FXX K '14" },
  { name: "Ferrari GTO '84" },
  { name: "Ferrari LaFerrari '13" },
  { name: "Ferrari Testarossa '91" },
  { name: "Ferrari Vision Gran Turismo" },
  { name: "Ford Escort RS Cosworth '92" },
  { name: "Ford F-150 SVT Raptor '11" },
  { name: "Ford Focus Gr.B Rally Car" },
  { name: "Ford Focus RS '18" },
  { name: "Ford Focus ST '15" },
  { name: "Ford GT '06" },
  { name: "Ford GT '17" },
  { name: "Ford GT LM Race Car Spec II" },
  { name: "Ford GT LM Spec II Test Car" },
  { name: "Ford GT Race Car '18" },
  { name: "Ford GT40 Mark I '66" },
  { name: "Ford Mark IV Race Car '67" },
  { name: "Ford Mustang Boss 429 '69" },
  { name: "Ford Mustang GT Premium Fastback '15" },
  { name: "Ford Mustang Gr.3" },
  { name: "Ford Mustang Gr.3 Road Car" },
  { name: "Ford Mustang Gr.4" },
  { name: "Ford Mustang Gr.B Rally Car" },
  { name: "Ford Mustang Mach 1 '71" },
  { name: "Ford Shelby GT350R '16" },
  { name: "Ford Sierra RS 500 Cosworth '87" },
  { name: "GReddy Fugu Z" },
  { name: "GT by Citroën Gr.4" },
  { name: "GT by Citroën Race Car (Gr.3)" },
  { name: "GT by Citroën Road Car" },
  { name: "Garage RCR Civic" },
  { name: "Genesis G70 3.3T AWD Prestige Package '22" },
  { name: "Genesis G70 GR4" },
  { name: "Genesis X GR3" },
  { name: "Genesis X Gran Berlinetta Vision Gran Turismo Concept" },
  { name: "Genesis X Gran Racer Vision Gran Turismo Concept" },
  { name: "Gran Turismo F1500T-A" },
  { name: "Gran Turismo F3500-A" },
  { name: "Gran Turismo F3500-B" },
  { name: "Gran Turismo Racing Kart 125 Shifter" },
  { name: "Gran Turismo Red Bull X2014 Junior" },
  { name: "Gran Turismo Red Bull X2014 Standard" },
  { name: "Gran Turismo Red Bull X2019 Competition" },
  { name: "Greening Auto Company Maverick" },
  { name: "HYUNDAI N 2025 Vision Gran Turismo" },
  { name: "HYUNDAI N 2025 Vision Gran Turismo (Gr.1)" },
  { name: "Honda Beat '91" },
  { name: "Honda CR-V e:HEV EX・Black Edition '21" },
  { name: "Honda Civic Si Extra (EF) '87" },
  { name: "Honda Civic SiR･II (EG) '93" },
  { name: "Honda Civic Type R (EK) '97" },
  { name: "Honda Civic Type R (EK) '98" },
  { name: "Honda Civic Type R (EK) Touring Car" },
  { name: "Honda Civic Type R (FK2) '15" },
  { name: "Honda Civic Type R (FL5) '22" },
  { name: "Honda Civic Type R Limited Edition (FK8) '20" },
  { name: "Honda Fit Hybrid '14" },
  { name: "Honda Integra Type R (DC2) '95" },
  { name: "Honda Integra Type R (DC2) '98" },
  { name: "Honda N-ONE RS '22" },
  { name: "Honda NSX '17" },
  { name: "Honda NSX CONCEPT-GT '16" },
  { name: "Honda NSX GT500 '00" },
  { name: "Honda NSX GT500 '08" },
  { name: "Honda NSX Gr.3" },
  { name: "Honda NSX Gr.4" },
  { name: "Honda NSX Gr.B Rally Car" },
  { name: "Honda NSX Type R '02" },
  { name: "Honda NSX Type R '92" },
  { name: "Honda Project 2&4 powered by RC213V" },
  { name: "Honda RA272 '65" },
  { name: "Honda S2000 '99" },
  { name: "Honda S660 '15" },
  { name: "Honda S800 '66" },
  { name: "Honda Sports Vision Gran Turismo" },
  { name: "Hyundai ELANTRA N '23" },
  { name: "Hyundai Genesis Coupe 3.8 Track '13" },
  { name: "Hyundai Genesis Gr.3" },
  { name: "Hyundai Genesis Gr.4" },
  { name: "Hyundai Genesis Gr.B Rally Car" },
  { name: "Hyundai IONIQ 5 N '24" },
  { name: "INFINITI CONCEPT Vision Gran Turismo" },
  { name: "IsoRivolta Zagato Vision Gran Turismo" },
  { name: "Italdesign EXENEO Vision Gran Turismo Off-road Mode" },
  { name: "Italdesign EXENEO Vision Gran Turismo Street Mode" },
  { name: "Jaguar D-type '54" },
  { name: "Jaguar E-type Coupé '61" },
  { name: "Jaguar F-type Gr.3" },
  { name: "Jaguar F-type Gr.4" },
  { name: "Jaguar F-type R Coupé '14" },
  { name: "Jaguar Vision Gran Turismo Coupé" },
  { name: "Jaguar Vision Gran Turismo Roadster" },
  { name: "Jaguar Vision Gran Turismo SV" },
  { name: "Jaguar XJ13 '66" },
  { name: "Jaguar XJ220 '92" },
  { name: "Jaguar XJR-9 '88" },
  { name: "Jeep Willys MB '45" },
  { name: "KTM X-BOW R '12" },
  { name: "LEXUS LF-LC GT \"Vision Gran Turismo\"" },
  { name: "Lambo V12 Vision Gran Turismo" },
  { name: "Lamborghini Aventador LP 700-4 '11" },
  { name: "Lamborghini Aventador LP 750-4 Superveloce '15" },
  { name: "Lamborghini Countach 25th Anniversary '88" },
  { name: "Lamborghini Countach LP400 '74" },
  { name: "Lamborghini Diablo GT '00" },
  { name: "Lamborghini Gallardo LP 560-4 '08" },
  { name: "Lamborghini Huracán GT3 '15" },
  { name: "Lamborghini Huracán Gr.4" },
  { name: "Lamborghini Huracán LP 610-4 '15" },
  { name: "Lamborghini Miura P400 Bertone Prototype '67" },
  { name: "Lamborghini Murciélago LP 640 '09" },
  { name: "Lamborghini Urus '18" },
  { name: "Lamborghini Veneno '14" },
  { name: "Lancia Delta HF Integrale Evoluzione '91" },
  { name: "Lancia Delta HF Integrale Rally Car '92" },
  { name: "Lancia Stratos '73" },
  { name: "Lexus LC500 '17" },
  { name: "Lexus LFA '10" },
  { name: "Lexus RC F '14" },
  { name: "Lexus RC F GT3 '17" },
  { name: "Lexus RC F GT3 prototype '16" },
  { name: "Lexus RC F GT500 '16" },
  { name: "Lexus RC F Gr.4" },
  { name: "Lexus SC430 GT500 '08" },
  { name: "MAZDA RX-VISION GT3 CONCEPT" },
  { name: "MAZDA SPIRIT RACING ROADSTER 12R '25" },
  { name: "MAZDA3 Gr.4" },
  { name: "MAZDA3 X Burgundy Selection '19" },
  { name: "MINI Clubman Vision Gran Turismo" },
  { name: "MINI Cooper S '05" },
  { name: "Maserati A6GCS/53 Spyder '54" },
  { name: "Maserati GranTurismo S '08" },
  { name: "Maserati MC20 '20" },
  { name: "Maserati Merak SS '80" },
  { name: "Mazda 787B '91" },
  { name: "Mazda Atenza Gr.3" },
  { name: "Mazda Atenza Gr.3 Road Car" },
  { name: "Mazda Atenza Gr.4" },
  { name: "Mazda Atenza Sedan XD L Package '15" },
  { name: "Mazda CX-30 X Smart Edition '21" },
  { name: "Mazda Demio XD Touring '15" },
  { name: "Mazda Eunos Roadster (NA Special Package) '89" },
  { name: "Mazda LM55 Vision Gran Turismo" },
  { name: "Mazda LM55 Vision Gran Turismo (Gr.1)" },
  { name: "Mazda RX-7 GT-X (FC) '90" },
  { name: "Mazda RX-7 Spirit R Type A (FD) '02" },
  { name: "Mazda RX-8 Spirit R '12" },
  { name: "Mazda RX-VISION '15" },
  { name: "Mazda RX500 '70" },
  { name: "Mazda Roadster NR-A (ND) '22" },
  { name: "Mazda Roadster S (ND) '15" },
  { name: "Mazda Roadster Touring Car" },
  { name: "McLaren 650S Coupe '14" },
  { name: "McLaren 650S GT3 '15" },
  { name: "McLaren 650S Gr.4" },
  { name: "McLaren F1 '94" },
  { name: "McLaren F1 GTR - BMW '95" },
  { name: "McLaren MP4-12C '10" },
  { name: "McLaren MP4/4 '88" },
  { name: "McLaren P1 GTR '16" },
  { name: "McLaren Ultimate Vision Gran Turismo" },
  { name: "McLaren Ultimate Vision Gran Turismo (Gr.1)" },
  { name: "Mercedes-AMG C 63 S '15" },
  { name: "Mercedes-AMG GT Black Series '20" },
  { name: "Mercedes-AMG GT R '17" },
  { name: "Mercedes-AMG GT S '15" },
  { name: "Mercedes-AMG GT Safety Car" },
  { name: "Mercedes-AMG GT3 '16" },
  { name: "Mercedes-AMG GT3 '20" },
  { name: "Mercedes-Benz 190 E 2.5-16 Evolution II '91" },
  { name: "Mercedes-Benz 300 SEL 6.8 AMG '71" },
  { name: "Mercedes-Benz 300 SL (W194) '52" },
  { name: "Mercedes-Benz 300 SL Coupé '54" },
  { name: "Mercedes-Benz A 45 AMG 4MATIC '13" },
  { name: "Mercedes-Benz AMG Vision Gran Turismo" },
  { name: "Mercedes-Benz AMG Vision Gran Turismo Racing Series" },
  { name: "Mercedes-Benz CLK-LM '98" },
  { name: "Mercedes-Benz S Barker Tourer '29" },
  { name: "Mercedes-Benz SLR McLaren '09" },
  { name: "Mercedes-Benz SLS AMG '10" },
  { name: "Mercedes-Benz SLS AMG GT3 '11" },
  { name: "Mercedes-Benz SLS AMG Gr.4" },
  { name: "Mercedes-Benz Unimog Type 411 '62" },
  { name: "Mercedes-Benz W 196 R '55" },
  { name: "Mine's BNR34 GT-R N1 base" },
  { name: "Mini-Cooper 'S' '65" },
  { name: "Mitsubishi Concept XR-PHEV EVOLUTION Vision Gran Turismo" },
  { name: "Mitsubishi FTO GP Version R '97" },
  { name: "Mitsubishi GTO Twin Turbo '91" },
  { name: "Mitsubishi Lancer Evolution Final Edition '15" },
  { name: "Mitsubishi Lancer Evolution Final Edition Gr.3" },
  { name: "Mitsubishi Lancer Evolution Final Edition Gr.4" },
  { name: "Mitsubishi Lancer Evolution Final Edition Gr.B Rally Car" },
  { name: "Mitsubishi Lancer Evolution Final Edition Gr.B Road Car" },
  { name: "Mitsubishi Lancer Evolution III GSR '95" },
  { name: "Mitsubishi Lancer Evolution IV GSR '96" },
  { name: "Mitsubishi Lancer Evolution IX MR GSR '06" },
  { name: "Mitsubishi Lancer Evolution V GSR '98" },
  { name: "Mitsubishi Lancer Evolution VI GSR T.M. EDITION Special Color Package '99" },
  { name: "Mitsubishi Lancer Evolution VIII MR GSR '04" },
  { name: "NISMO 400R '95" },
  { name: "NISMO R34 GT-R Z-tune '05" },
  { name: "NISSAN CONCEPT 2020 Vision Gran Turismo" },
  { name: "Nissan 180SX Type X '96" },
  { name: "Nissan Fairlady 240ZG (HS30) '71" },
  { name: "Nissan Fairlady Z (Z34) '08" },
  { name: "Nissan Fairlady Z 300ZX TwinTurbo 2seater (Z32) '89" },
  { name: "Nissan Fairlady Z 432 '69" },
  { name: "Nissan Fairlady Z Version S (Z33) '07" },
  { name: "Nissan GT-R GT500 '08" },
  { name: "Nissan GT-R GT500 '99" },
  { name: "Nissan GT-R Gr.4" },
  { name: "Nissan GT-R Gr.B Rally Car" },
  { name: "Nissan GT-R LM NISMO '15" },
  { name: "Nissan GT-R NISMO '17" },
  { name: "Nissan GT-R NISMO (R32) '90" },
  { name: "Nissan GT-R NISMO GT3 '13" },
  { name: "Nissan GT-R NISMO GT3 '18" },
  { name: "Nissan GT-R NISMO GT500 '16" },
  { name: "Nissan GT-R Premium edition '17" },
  { name: "Nissan GT-R Premium edition T-spec '24" },
  { name: "Nissan GT-R Safety Car" },
  { name: "Nissan Qashqai Tekna 190 2wd e-Power '22" },
  { name: "Nissan R92CP '92" },
  { name: "Nissan Sileighty '98" },
  { name: "Nissan Silvia K's Aero (S14) '96" },
  { name: "Nissan Silvia K's Dia Selection (S13) '90" },
  { name: "Nissan Silvia K's Type S (S14) '94" },
  { name: "Nissan Silvia Q's (S13) '88" },
  { name: "Nissan Silvia spec-R Aero (S15) '02" },
  { name: "Nissan Silvia spec-R Aero (S15) Touring Car" },
  { name: "Nissan Skyline 2000GT-R (KPGC110) '73" },
  { name: "Nissan Skyline GT-R V･spec (R33) '97" },
  { name: "Nissan Skyline GT-R V･spec II (R32) '94" },
  { name: "Nissan Skyline GT-R V･spec II Nür (R34) '02" },
  { name: "Nissan Skyline GTS-R (R31) '87" },
  { name: "Nissan Skyline Hard Top 2000GT-R (KPGC10) '70" },
  { name: "Nissan Skyline Super Silhouette Group 5 '84" },
  { name: "Nissan Z Performance '23" },
  { name: "Opel Corsa GSE Vision Gran Turismo" },
  { name: "PEUGEOT Vision Gran Turismo" },
  { name: "PEUGEOT Vision Gran Turismo (Gr.3)" },
  { name: "Pagani Huayra '13" },
  { name: "Pagani Zonda R '09" },
  { name: "Peugeot 205 GTI '88" },
  { name: "Peugeot 205 Turbo 16 Evolution 2 '86" },
  { name: "Peugeot 208 GTi by Peugeot Sport '14" },
  { name: "Peugeot 908 HDi FAP '10" },
  { name: "Peugeot L500R HYbrid Vision Gran Turismo, 2017" },
  { name: "Peugeot L750R HYbrid Vision Gran Turismo, 2017" },
  { name: "Peugeot RCZ GT Line '15" },
  { name: "Peugeot RCZ Gr.3" },
  { name: "Peugeot RCZ Gr.3 Road Car" },
  { name: "Peugeot RCZ Gr.4" },
  { name: "Peugeot RCZ Gr.B Rally Car" },
  { name: "Peugeot SUV 2008 Allure '21" },
  { name: "Plymouth Superbird '70" },
  { name: "Plymouth XNR Ghia Roadster '60" },
  { name: "Polestar 5 Performance '26" },
  { name: "Pontiac Firebird Trans Am '78" },
  { name: "Pontiac GTO 'The Judge' '69" },
  { name: "Porsche 356 A/1500 GS Carrera '56" },
  { name: "Porsche 356 A/1500 GS GT Carrera Speedster '56" },
  { name: "Porsche 911 Carrera RS (901) '73" },
  { name: "Porsche 911 Carrera RS (964) '92" },
  { name: "Porsche 911 Carrera RS (993) '95" },
  { name: "Porsche 911 Carrera RS Club Sport (993) '95" },
  { name: "Porsche 911 GT1 Strassenversion '97" },
  { name: "Porsche 911 GT3 (996) '01" },
  { name: "Porsche 911 GT3 (997) '09" },
  { name: "Porsche 911 GT3 RS (991) '16" },
  { name: "Porsche 911 GT3 RS (992) '22" },
  { name: "Porsche 911 RSR (991) '17" },
  { name: "Porsche 911 Turbo (930) '81" },
  { name: "Porsche 911 Turbo S (992) '20" },
  { name: "Porsche 917 LIVING LEGEND" },
  { name: "Porsche 917K '70" },
  { name: "Porsche 918 Spyder '13" },
  { name: "Porsche 919 Hybrid '16" },
  { name: "Porsche 959 '87" },
  { name: "Porsche 962 C '88" },
  { name: "Porsche Carrera GT '04" },
  { name: "Porsche Carrera GTS (904) '64" },
  { name: "Porsche Cayman GT4 '16" },
  { name: "Porsche Cayman GT4 Clubsport '16" },
  { name: "Porsche Mission X '23" },
  { name: "Porsche Spyder type 550/1500RS '55" },
  { name: "Porsche Taycan Turbo S '19" },
  { name: "Porsche Vision Gran Turismo" },
  { name: "Porsche Vision Gran Turismo Spyder" },
  { name: "RE Amemiya FD3S RX-7" },
  { name: "RUF CTR3 '07" },
  { name: "RUF RGT 4.2 '16" },
  { name: "Radical SR3 SL '13" },
  { name: "Renault Avantime 3.0 V6 24V '02" },
  { name: "Renault Espace F1 '95" },
  { name: "Renault Kangoo 1.4 '01" },
  { name: "Renault R4 GTL '85" },
  { name: "Renault R5 Turbo '80" },
  { name: "Renault R8 Gordini '66" },
  { name: "Renault Sport Clio R.S. 220 EDC Trophy '15" },
  { name: "Renault Sport Clio R.S. 220 EDC Trophy '16" },
  { name: "Renault Sport Clio V6 24V '00" },
  { name: "Renault Sport Mégane Gr.4" },
  { name: "Renault Sport Mégane R.S. Trophy '11" },
  { name: "Renault Sport Mégane R.S. Trophy Safety Car" },
  { name: "Renault Sport Mégane Trophy '11" },
  { name: "Renault Sport R.S.01 '16" },
  { name: "Renault Sport R.S.01 GT3 '16" },
  { name: "Roadster Shop Rampage" },
  { name: "SUBARU VIZIV GT Vision Gran Turismo" },
  { name: "SUZUKI Vision Gran Turismo" },
  { name: "SUZUKI Vision Gran Turismo (Gr.3 Version)" },
  { name: "Sauber Mercedes C9 '89" },
  { name: "Shelby Cobra 427 '66" },
  { name: "Shelby Cobra Daytona Coupe '64" },
  { name: "Shelby G.T.350 '65" },
  { name: "Subaru BRZ Drift Car '17" },
  { name: "Subaru BRZ GT300 '21" },
  { name: "Subaru BRZ S '15" },
  { name: "Subaru BRZ S '21" },
  { name: "Subaru BRZ STI Sport '18" },
  { name: "Subaru Impreza 22B-STi Version '98" },
  { name: "Subaru Impreza Coupe WRX Type R STi Version VI '99" },
  { name: "Subaru Impreza Rally Car '98" },
  { name: "Subaru Impreza Sedan WRX STi '04" },
  { name: "Subaru WRX Gr.3" },
  { name: "Subaru WRX Gr.4" },
  { name: "Subaru WRX Gr.B Rally Car" },
  { name: "Subaru WRX Gr.B Road Car" },
  { name: "Subaru WRX STI Isle of Man Time Attack Car '16" },
  { name: "Subaru WRX STI Type S '14" },
  { name: "Suzuki Cappuccino (EA11R) '91" },
  { name: "Suzuki Carry KC '12" },
  { name: "Suzuki Jimny Sierra JC '18" },
  { name: "Suzuki Jimny XC '18" },
  { name: "Suzuki Swift Sport '07" },
  { name: "Suzuki Swift Sport '17" },
  { name: "Suzuki Swift Sport KATANA Edition Gr.4" },
  { name: "Suzuki V6 Escudo Pikes Peak Special '98" },
  { name: "TOYOTA 86 GT '15" },
  { name: "TOYOTA 86 GT\"Limited\" '16" },
  { name: "TOYOTA 86 Gr.4" },
  { name: "TOYOTA 86 Gr.B Rally Car" },
  { name: "TOYOTA GR010 HYBRID '21" },
  { name: "TOYOTA S-FR '15" },
  { name: "TOYOTA S-FR Racing Concept '16" },
  { name: "TVR Tuscan Speed 6 '00" },
  { name: "Tesla Model 3 Performance '23" },
  { name: "Tesla Model S Signature Performance '12" },
  { name: "Toyota 2000GT '67" },
  { name: "Toyota 86 GRMN '16" },
  { name: "Toyota Alphard Executive Lounge '18" },
  { name: "Toyota Ambulance Himedic '21" },
  { name: "Toyota Aqua S '11" },
  { name: "Toyota C-HR S '18" },
  { name: "Toyota Celica GT-FOUR (ST205) '94" },
  { name: "Toyota Celica GT-FOUR Rally Car (ST205) '95" },
  { name: "Toyota Corolla Levin 3door 1600GT APEX (AE86) '83" },
  { name: "Toyota Crown Athlete G '13" },
  { name: "Toyota Crown Athlete G Safety Car" },
  { name: "Toyota FT-1" },
  { name: "Toyota FT-1 Vision Gran Turismo" },
  { name: "Toyota FT-1 Vision Gran Turismo (Gr.3)" },
  { name: "Toyota GR Corolla MORIZO Edition '22" },
  { name: "Toyota GR Supra RZ '19" },
  { name: "Toyota GR Supra RZ '20" },
  { name: "Toyota GR Supra Race Car '19" },
  { name: "Toyota GR Supra Racing Concept '18" },
  { name: "Toyota GR Yaris 1st Edition RZ \"High performance\" '20" },
  { name: "Toyota GR86 RZ '21" },
  { name: "Toyota GT-One (TS020) '99" },
  { name: "Toyota Hiace Van DX '16" },
  { name: "Toyota Land Cruiser FJ40V '74" },
  { name: "Toyota MR2 GT-S '97" },
  { name: "Toyota Prius G '09" },
  { name: "Toyota RAV4 Adventure '20" },
  { name: "Toyota Sports 800 '65" },
  { name: "Toyota Sprinter Trueno 3door 1600GT APEX (AE86) '83" },
  { name: "Toyota Supra 3.0GT Turbo A '88" },
  { name: "Toyota Supra GT500 '97" },
  { name: "Toyota Supra RZ '97" },
  { name: "Toyota TS030 Hybrid '12" },
  { name: "Toyota TS050 - Hybrid '16" },
  { name: "Toyota Trueno 3door 1600GT APEX (AE86 Shuichi Shigeno Version)" },
  { name: "Toyota Tundra TRD Pro '19" },
  { name: "Volkswagen 1200 '66" },
  { name: "Volkswagen Beetle Gr.3" },
  { name: "Volkswagen GTI Roadster Vision Gran Turismo" },
  { name: "Volkswagen GTI Supersport Vision Gran Turismo" },
  { name: "Volkswagen GTI Vision Gran Turismo (Gr.3)" },
  { name: "Volkswagen Golf I GTI '83" },
  { name: "Volkswagen Golf VII GTI '14" },
  { name: "Volkswagen ID.R '19" },
  { name: "Volkswagen Polo GTI '14" },
  { name: "Volkswagen Sambabus Typ 2 (T1) '62" },
  { name: "Volkswagen Scirocco Gr.4" },
  { name: "Volkswagen Scirocco R '10" },
  { name: "Volvo 240 SE Estate '93" },
  { name: "Volvo V40 T5 R-Design '13" },
  { name: "Wicked Fabrication GT 51" },
  { name: "Škoda Vision Gran Turismo" }
];

// --- COMPLETE TRACK LIST WITH PROFILES ---

export const TRACKS: Track[] = [
  // --- DRY TRACKS (S01-S18, C01-C06) ---
  
  // 1. Dry + Extended 24h Time
  // Colorado Springs, Daytona, Northern Isle, Route X, Mount Panorama
  { 
    id: 'colorado_springs', name: 'Colorado Springs (Dirt)', location: 'USA', variations: ['Lake', 'Lake Reverse'],
    availableTimes: TIMES_EXTENDED_24H, availableWeather: WEATHER_DRY
  },
  { 
    id: 'daytona', name: 'Daytona International Speedway', location: 'USA', variations: ['Road Course', 'Tri-Oval'],
    availableTimes: TIMES_EXTENDED_24H, availableWeather: WEATHER_DRY
  },
  { 
    id: 'northern_isle', name: 'Northern Isle Speedway', location: 'USA', variations: ['Full Course'],
    availableTimes: TIMES_EXTENDED_24H, availableWeather: WEATHER_DRY
  },
  { 
    id: 'ss_route_x', name: 'Special Stage Route X', location: 'USA', variations: ['Full Course'],
    availableTimes: TIMES_EXTENDED_24H, availableWeather: WEATHER_DRY
  },
  { 
    id: 'bathurst', name: 'Mount Panorama', location: 'Australia', variations: ['Full Course'],
    availableTimes: TIMES_EXTENDED_24H, availableWeather: WEATHER_DRY
  },

  // 2. Dry + Standard Time (Dawn -> Night)
  // Interlagos, Blue Moon, Fisherman's, Grand Valley, Lake Louise, Road Atlanta, Trial Mountain, Watkins Glen, Alsace, Maggiore, Catalunya, St Croix, Deep Forest, Dragon Trail, Eiger, Autopolis, Broad Bean, High Speed Ring, Kyoto
  { 
    id: 'interlagos', name: 'Autódromo de Interlagos', location: 'Brazil', variations: ['Full Course'],
    availableTimes: ["Early Dawn", "Dawn", "Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight"], 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'blue_moon', name: 'Blue Moon Bay Speedway', location: 'USA', variations: ['Full Course', 'Reverse'],
    availableTimes: TIMES_STANDARD, availableWeather: WEATHER_DRY
  },
  { 
    id: 'fishermans', name: 'Fishermans Ranch (Dirt)', location: 'USA', variations: ['Forward', 'Reverse'],
    availableTimes: ["Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight"], 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'grand_valley_hwy1', name: 'Grand Valley - Highway 1', location: 'USA', variations: ['Forward', 'Reverse'],
    availableTimes: ["Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'lake_louise_long', name: 'Lake Louise Long Track (Snow)', location: 'Canada', variations: ['Forward', 'Reverse'],
    availableTimes: ["Early Dawn", "Dawn", "Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'road_atlanta', name: 'Michelin Raceway Road Atlanta', location: 'USA', variations: ['Full Course'],
    availableTimes: TIMES_EXTENDED_24H, availableWeather: WEATHER_DRY
  },
  { 
    id: 'trial_mountain', name: 'Trial Mountain Circuit', location: 'USA', variations: ['Forward', 'Reverse'],
    availableTimes: ["Dawn", "Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'watkins_glen', name: 'Watkins Glen International', location: 'USA', variations: ['Long Course', 'Short Course'],
    availableTimes: ["Early Dawn", "Dawn", "Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'laguna_seca', name: 'WeatherTech Raceway Laguna Seca', location: 'USA', variations: ['Full Course'],
    availableTimes: TIMES_LIMITED_DAY_PLUS, 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'willow_big', name: 'Willow Springs: Big Willow', location: 'USA', variations: ['Full Course'],
    availableTimes: ["Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'alsace_village', name: 'Alsace - Village', location: 'France', variations: ['Forward', 'Reverse'],
    availableTimes: ["Dawn", "Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'maggiore_full', name: 'Autodrome Lago Maggiore - Full Course', location: 'Italy', variations: ['Forward', 'Reverse'],
    availableTimes: ["Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight"], 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'monza', name: 'Autodromo Nazionale Monza', location: 'Italy', variations: ['Full Course', 'No Chicane'],
    availableTimes: TIMES_LIMITED_DAY, availableWeather: WEATHER_DRY
  },
  { 
    id: 'brands_hatch', name: 'Brands Hatch', location: 'UK', variations: ['Grand Prix Circuit', 'Indy Circuit'],
    availableTimes: TIMES_LIMITED_DAY, availableWeather: WEATHER_DRY
  },
  { 
    id: 'catalunya', name: 'Circuit de Barcelona-Catalunya', location: 'Spain', variations: ['GP Layout', 'GP No Chicane'],
    availableTimes: ["Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'st_croix_a', name: 'Circuit de Sainte-Croix - A', location: 'France', variations: ['Forward', 'Reverse'],
    availableTimes: ["Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'deep_forest', name: 'Deep Forest Raceway', location: 'Switzerland', variations: ['Forward', 'Reverse'],
    availableTimes: ["Dawn", "Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'dragon_seaside', name: 'Dragon Trail - Seaside', location: 'Croatia', variations: ['Forward', 'Reverse'],
    availableTimes: ["Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'eiger', name: 'Eiger Nordwand', location: 'Switzerland', variations: ['Forward', 'Reverse'],
    availableTimes: ["Dawn", "Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'goodwood', name: 'Goodwood Motor Circuit', location: 'UK', variations: ['Full Course'],
    availableTimes: TIMES_LIMITED_DAY, availableWeather: WEATHER_DRY
  },
  { 
    id: 'sardegna_road_a', name: 'Sardegna - Road Track - A', location: 'Italy', variations: ['Forward', 'Reverse'],
    availableTimes: TIMES_LIMITED_DAY, availableWeather: WEATHER_DRY
  },
  { 
    id: 'sardegna_windmills', name: 'Sardegna - Windmills (Dirt)', location: 'Italy', variations: ['Forward', 'Reverse'],
    availableTimes: ["Dawn", "Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'broad_bean', name: 'Broad Bean Raceway', location: 'Japan', variations: ['Forward', 'Reverse'],
    availableTimes: ["Dawn", "Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_DRY
  },
  { 
    id: 'high_speed_ring', name: 'High Speed Ring', location: 'Japan', variations: ['Forward', 'Reverse'],
    availableTimes: ["Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight"], 
    availableWeather: WEATHER_DRY
  },
  
  // --- WET TRACKS (All Weather + Specific Times) ---

  // Le Mans (24h + Rain)
  { 
    id: 'lemans', name: '24 Heures du Mans Racing Circuit', location: 'France', variations: ['Full Circuit', 'No Chicane'],
    availableTimes: TIMES_EXTENDED_24H, availableWeather: WEATHER_ALL
  },
  // Spa (Limited Day + Rain)
  { 
    id: 'spa', name: 'Circuit de Spa-Francorchamps', location: 'Belgium', variations: ['Full Course', '24h Layout'],
    availableTimes: ["Early Morning", "Late Morning", "Afternoon", "Evening"], availableWeather: WEATHER_ALL
  },
  // Nurburgring (Day + Rain)
  { 
    id: 'nurb_nord', name: 'Nürburgring Nordschleife', location: 'Germany', variations: ['Nordschleife', 'Tourist'],
    availableTimes: ["Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight"], availableWeather: WEATHER_ALL
  },
  { 
    id: 'nurb_24h', name: 'Nürburgring 24h', location: 'Germany', variations: ['24h', 'Endurance'],
    availableTimes: ["Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight"], availableWeather: WEATHER_ALL
  },
  // Red Bull Ring (Day + Rain)
  { 
    id: 'red_bull', name: 'Red Bull Ring', location: 'Austria', variations: ['Full Course', 'Short Track'],
    availableTimes: ["Dawn", "Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_ALL
  },
  // Autopolis (Day + Rain)
  { 
    id: 'autopolis', name: 'Autopolis International Racing Course', location: 'Japan', variations: ['Full Course', 'Short Course'],
    availableTimes: ["Dawn", "Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_ALL
  },
  // Fuji (Day + Rain)
  { 
    id: 'fuji', name: 'Fuji International Speedway', location: 'Japan', variations: ['Full Course', 'Short Course'],
    availableTimes: ["Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset"], 
    availableWeather: WEATHER_ALL
  },
  // Kyoto (Day + Rain)
  { 
    id: 'kyoto_combined', name: 'Kyoto Driving Park - Yamagiwa+Miyabi', location: 'Japan', variations: ['Forward', 'Reverse'],
    availableTimes: ["Dawn", "Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_ALL
  },
  // Suzuka (Day + Rain)
  { 
    id: 'suzuka', name: 'Suzuka Circuit', location: 'Japan', variations: ['Full Course', 'East Course'],
    availableTimes: ["Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight", "Night"], 
    availableWeather: WEATHER_ALL
  },
  // Tokyo Expressway (24h + Rain)
  { 
    id: 'tokyo_central', name: 'Tokyo Expressway - Central', location: 'Japan', variations: ['Clockwise', 'Counterclockwise'],
    availableTimes: TIMES_EXTENDED_24H, availableWeather: WEATHER_ALL
  },
  { 
    id: 'tokyo_east', name: 'Tokyo Expressway - East', location: 'Japan', variations: ['Clockwise', 'Counterclockwise'],
    availableTimes: TIMES_EXTENDED_24H, availableWeather: WEATHER_ALL
  },
  { 
    id: 'tokyo_south', name: 'Tokyo Expressway - South', location: 'Japan', variations: ['Clockwise', 'Counterclockwise'],
    availableTimes: TIMES_EXTENDED_24H, availableWeather: WEATHER_ALL
  },
  // Tsukuba (Day + Rain)
  { 
    id: 'tsukuba', name: 'Tsukuba Circuit', location: 'Japan', variations: ['Full Course'],
    availableTimes: ["Dawn", "Sunrise", "Early Morning", "Late Morning", "Afternoon", "Evening", "Sunset", "Twilight"], 
    availableWeather: WEATHER_ALL
  },

  // --- NEW CIRCUITS ---
  { 
    id: 'cgv', name: 'Circuit Gilles-Villeneuve', location: 'Canada', variations: ['Full Course'],
    availableTimes: TIMES_STANDARD, availableWeather: WEATHER_DRY
  },
  { 
    id: 'yas_marina', name: 'Yas Marina Circuit', location: 'UAE', variations: ['Full Course'],
    availableTimes: TIMES_EXTENDED_24H, availableWeather: WEATHER_DRY
  }
];

export const GT7_LINKS = {
  tracks: 'https://www.gran-turismo.com/gb/gt7/tracklist/',
  cars: 'https://www.gran-turismo.com/us/gt7/carlist/'
};